FIX: Use string value for Stylix nixvim plugin option
Fix for commit 6098979 - the plugin option expects a string value:
- Changed: pkgs.vimPlugins.base16-nvim (package derivation - incorrect)
- To: "base16-nvim" (string enum value - correct)

Applied to both NixOS and home-manager Stylix modules.

Valid plugin values are: "base16-nvim" or "mini.base16"

This fixes the build error:
  error: A definition for option `...stylix.targets.nixvim.plugin'
  is not of type `one of "base16-nvim", "mini.base16"'